apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: s2i-demo-pipeline
spec:
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/dbais76/testrep'
        - name: revision
          value: main
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:1a50511583fc02a27012d17d942e247813404104ddd282d7e26f99765174392c
        - name: userHome
          value: /home/git
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: demowk
    - name: s2i-php
      params:
        - name: VERSION
          value: latest
        - name: PATH_CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'true'
        - name: IMAGE
          value: 'quay.io/dbais76/demo-repo:120'
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:00795fafdab9bbaa22cd29d1faa1a01e604e4884a2c935c1bf8e3d1f0ad1c084
        - name: SKIP_PUSH
          value: 'false'
        - name: ENV_VARS
          value: []
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: s2i-php
      workspaces:
        - name: source
          workspace: demowk
    - name: openshift-client
      params:
        - name: SCRIPT
          value: >-
            oc new-app --name demo --image quay.io/dbais76/demo-repo:120 -l app=demo -n prod; sleep 30 ; echo "Exposing service to get Route in project Prod " ; oc expose svc demo -n prod ; ROUTE_URL=$( oc get route demo -n prod -o template --template '{{ "http://" }}{{ .spec.host }}') ; echo "The Application is now accessible on $ROUTE_URL"
        - name: VERSION
          value: latest
      runAfter:
        - s2i-php
      taskRef:
        kind: ClusterTask
        name: openshift-client
  workspaces:
    - name: demowk
