apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    pipeline.openshift.io/started-by: developer
  resourceVersion: '280407'
  name: demo-pipelineine-y3cid7
  uid: 32ccd39e-098a-4588-bf6c-6c412ac06920
  creationTimestamp: '2023-10-06T05:37:33Z'
  generation: 1
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:pipeline.openshift.io/started-by': {}
          'f:labels':
            .: {}
            'f:tekton.dev/pipeline': {}
        'f:spec':
          .: {}
          'f:params': {}
          'f:pipelineRef':
            .: {}
            'f:name': {}
          'f:resources': {}
          'f:status': {}
          'f:workspaces': {}
      manager: Mozilla
      operation: Update
      time: '2023-10-06T05:37:33Z'
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:finalizers':
            .: {}
            'v:"chains.tekton.dev/pipelinerun"': {}
      manager: openshift-pipelines-chains-controller
      operation: Update
      time: '2023-10-06T05:37:33Z'
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          .: {}
          'f:childReferences': {}
          'f:conditions': {}
          'f:pipelineSpec':
            .: {}
            'f:tasks': {}
            'f:workspaces': {}
          'f:startTime': {}
      manager: openshift-pipelines-controller
      operation: Update
      subresource: status
      time: '2023-10-06T05:37:33Z'
  namespace: demo
  finalizers:
    - chains.tekton.dev/pipelinerun
  labels:
    tekton.dev/pipeline: demo-pipelineine
spec:
  pipelineRef:
    name: demo-pipelineine
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
    - name: demowk
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: nfs-storage
          volumeMode: Filesystem
        status: {}
status:
  childReferences:
    - apiVersion: tekton.dev/v1beta1
      kind: TaskRun
      name: demo-pipelineine-y3cid7-git-clone
      pipelineTaskName: git-clone
  conditions:
    - lastTransitionTime: '2023-10-06T05:37:33Z'
      message: 'Tasks Completed: 0 (Failed: 0, Cancelled 0), Incomplete: 3, Skipped: 0'
      reason: Running
      status: Unknown
      type: Succeeded
  pipelineSpec:
    tasks:
      - name: git-clone
        params:
          - name: url
            value: 'https://github.com/dbais76/testrep'
          - name: revision
            value: main
          - name: submodules
            value: 'true'
          - name: depth
            value: '1'
          - name: sslVerify
            value: 'true'
          - name: crtFileName
            value: ca-bundle.crt
          - name: deleteExisting
            value: 'true'
          - name: verbose
            value: 'true'
          - name: gitInitImage
            value: >-
              registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:1a50511583fc02a27012d17d942e247813404104ddd282d7e26f99765174392c
          - name: userHome
            value: /home/git
        taskRef:
          kind: ClusterTask
          name: git-clone
        workspaces:
          - name: output
            workspace: demowk
        status:
          reason: Failed
      - name: s2i-php
        params:
          - name: VERSION
            value: latest
          - name: PATH_CONTEXT
            value: .
          - name: TLSVERIFY
            value: 'true'
          - name: IMAGE
            value: 'quay.io/dbais76/demo-repo:120'
          - name: BUILDER_IMAGE
            value: >-
              registry.redhat.io/rhel8/buildah@sha256:00795fafdab9bbaa22cd29d1faa1a01e604e4884a2c935c1bf8e3d1f0ad1c084
          - name: SKIP_PUSH
            value: 'false'
          - name: ENV_VARS
            value: []
        runAfter:
          - git-clone
        taskRef:
          kind: ClusterTask
          name: s2i-php
        workspaces:
          - name: source
            workspace: demowk
        status:
          reason: Failed
      - name: openshift-client
        params:
          - name: SCRIPT
            value: >-
              oc new-app --name demo --image quay.io/dbais76/demo-repo:120 -l
              app=demo  echo "Exposing service to get Route " oc expose svc demo
              ROUTE_URL=$( oc get route demo -o template --template '{{
              "http://" }}{{ .spec.host }}') echo
              "***********************************************" echo "The
              Application is now accessible on $ROUTE_URL" echo
              "***********************************************"
          - name: VERSION
            value: latest
        runAfter:
          - s2i-php
        taskRef:
          kind: ClusterTask
          name: openshift-client
        status:
          reason: Failed
    workspaces:
      - name: demowk
  startTime: '2023-10-06T05:37:33Z'
